#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
详细诊断火山引擎 TOS 配置问题
"""
import base64

print("=" * 70)
print("火山引擎 TOS 配置诊断")
print("=" * 70)
print()

# 检查密钥格式
from config import ACCESS_KEY_ID, ACCESS_KEY_SECRET

print("当前配置:")
print("-" * 70)
print(f"Access Key ID: {ACCESS_KEY_ID}")
print(f"  长度: {len(ACCESS_KEY_ID)} 字符")
print()
print(f"Secret Access Key (原始): {ACCESS_KEY_SECRET}")
print(f"  长度: {len(ACCESS_KEY_SECRET)} 字符")

try:
    decoded = base64.b64decode(ACCESS_KEY_SECRET).decode('utf-8')
    print(f"Secret Access Key (Base64解码): {decoded}")
    print(f"  解码后长度: {len(decoded)} 字符")
except:
    print("  无法进行 Base64 解码")

print()
print("=" * 70)
print()

print("火山引擎 TOS 密钥格式说明:")
print("-" * 70)
print("标准的火山引擎密钥格式应该是：")
print()
print("Access Key ID 示例：")
print("  - 通常以 'AK' 开头")
print("  - 长度一般为 20-40 个字符")
print("  - 包含大小写字母和数字")
print("  - 例如: AKIAIOSFODNN7EXAMPLE")
print()
print("Secret Access Key 示例：")
print("  - 长度一般为 40 个字符左右")
print("  - 包含大小写字母、数字和特殊字符")
print("  - 例如: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY")
print("  - 注意：不应该是 Base64 编码的！")
print()
print("=" * 70)
print()

print("请检查以下事项：")
print("-" * 70)
print()
print("1. 确认密钥来源")
print("   - 登录火山引擎控制台")
print("   - 访问: https://console.volcengine.com/iam/keymanage/")
print("   - 查看或创建新的 Access Key")
print()
print("2. 密钥格式检查")
print("   - Access Key ID 应该直接复制，不需要任何编码")
print("   - Secret Access Key 也应该直接复制，不需要 Base64 编码")
print("   - 如果你看到的密钥已经是 Base64 编码的，可能是获取方式有误")
print()
print("3. Bucket 配置检查")
print("   - 访问: https://console.volcengine.com/tos/bucket/")
print("   - 确认 Bucket 名称是否为: public-260224")
print("   - 确认 Bucket 所在区域是否为: cn-beijing")
print()
print("4. 权限检查")
print("   - 确认该 Access Key 有权限访问 Bucket")
print("   - 检查 Bucket 的访问策略")
print("   - 确认该密钥未被禁用或删除")
print()
print("5. Endpoint 检查")
print("   - 外网: tos-cn-beijing.volces.com")
print("   - 内网: tos-cn-beijing.ivolces.com")
print("   - 确认使用的是正确的 Endpoint")
print()
print("=" * 70)
print()
print("建议操作：")
print("-" * 70)
print()
print("1. 重新获取密钥：")
print("   a) 登录火山引擎控制台")
print("   b) 访问 IAM 密钥管理页面")
print("   c) 创建新的 Access Key（或查看现有的）")
print("   d) 直接复制 Access Key ID 和 Secret Access Key")
print("   e) 不要进行任何编码或转换")
print()
print("2. 更新 config.py：")
print("   修改以下内容：")
print("   ACCESS_KEY_ID = '你的原始AccessKeyID'")
print("   ACCESS_KEY_SECRET = '你的原始SecretAccessKey'  # 不要 Base64 编码")
print()
print("3. 重新运行测试：")
print("   python test_credentials.py")
print()
print("=" * 70)
